/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardComponent: typeof import('./src/components/CardComponent.vue')['default']
    ProgressComponent: typeof import('./src/components/ProgressComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToolbarComponent: typeof import('./src/components/ToolbarComponent.vue')['default']
  }
}
